@host=http://localhost:5243

GET {{host}}/companias 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNWE4YjBjNi0wZTY0LTQzMTctYWEyNy03ZThiMDNkZDA2MzciLCJnaXZlbl9uYW1lIjoiQ2FybWVuIiwiZmFtaWx5X25hbWUiOiJTYW5jaGV6IiwianRpIjoiMWI3YTk5MmItZWNmZi00OGFmLWJlODQtZDg2YzJhOGI4ZjIwIiwiZXhwIjoxNzA4MjI4NTY5LCJpc3MiOiJDbGlja1ByZW1pdW0iLCJhdWQiOiJDbGlja1ByZW1pdW0gQVBJIn0.stx9AlFluuj9zknYxcTlg8rK1In2ugzxnsEmtffJVBg